version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
    container_name: proxy
    hostname: nginx
    ports:
        - "80:80" 
    depends_on:
        - aggregator-service
        
  content-db:
    image: 'mongo:focal'
    container_name: content-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: host
    volumes:
      - content-db-data:/data/db 
    restart: always

  user-interaction-db:
    image: 'mongo:focal'
    container_name: user-interaction-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: host
    volumes:
      - user-interaction-db-data:/data/db
    restart: always
    depends_on:
      - aggregator-service
  
  users-db:
    image: 'mongo:focal'
    container_name: users-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: host
    volumes:
    - users-db-data:/data/db
    restart: always
    depends_on:
      - aggregator-service

  aggregator-service:
    build: ./aggregator-service
    environment:
      - CONTENT_SERVICE=http://content-service:5000
    ports:
      - 3000:3000

  content-service:
    build: ./content-service
    ports:
      - 5000:5000
    depends_on:
      - content-db
      - aggregator-service

  user-interaction-service:
    build: ./user-interaction-service
    ports:
      - "4000:4000"
    depends_on:
      - user-interaction-db
      - aggregator-service
      - content-service

  users-service:
    build: ./user-service
    ports:
      - 7000:7000
    depends_on:
      - users-db
      - aggregator-service

volumes:
  content-db-data:
  user-interaction-db-data:
  users-db-data:

networks:
  default:
    driver: host